{ config, lib, sensibleLib }:
let
  terminal = lib.getExe (sensibleLib.getDefaultPackage config.sensible.terminal);
  browser = lib.getExe (sensibleLib.getDefaultPackage config.sensible.browser);
  launcherCmd = if config.sensible.launcher == "rofi"
    then ''"rofi" "-show" "drun"''
    else ''"walker"'';
  rofiBinds = lib.optionals (config.sensible.launcher == "rofi") [
    ''Mod+V { spawn "sh" "-c" "cliphist list | rofi -dmenu | cliphist decode | wl-copy"; }''
    ''Mod+Shift+X { spawn "sh" "-c" "format=\"$(echo -ne 'cmyk\\nhex\\nrgb\\nhsl\\nhsv' | rofi -dmenu)\" && sleep 0.7s && hyprpicker -af \"$format\""; }''
  ];
in ''
// Generated by sensible-nix
input {
    keyboard {
        xkb {
            layout "se"
        }
        track-layout "session"
    }
    touchpad {
        tap
        dwt
        natural-scroll
    }
}

output "*" {
    scale 1
}

layout {
    gaps 5
    focus-ring {
        width 2
        active-color "#4c7899"
        inactive-color "#323232"
    }
    shadow {
        on
        softness 30
        offset x=0 y=5
        color "#0000007f"
    }
}

spawn-at-startup "wlsunset" "-l" "-23" "-L" "-46"
spawn-at-startup "wl-paste" "--watch" "cliphist" "store"

window-rule {
    geometry-corner-radius 10
    clip-to-geometry true
}

binds {
    Mod+T { spawn "${terminal}"; }
    Mod+B { spawn "${browser}"; }
    Mod+R { spawn ${launcherCmd}; }
    Mod+Q { close-window; }
    Mod+F { maximize-column; }
    Mod+Shift+F { fullscreen-window; }
    Ctrl+Mod+F { toggle-floating; }

    Mod+H { focus-column-left; }
    Mod+L { focus-column-right; }
    Mod+K { focus-window-up-or-workspace-up; }
    Mod+J { focus-window-down-or-workspace-down; }

    Mod+Shift+H { move-column-left; }
    Mod+Shift+L { move-column-right; }
    Mod+Shift+K { move-window-up-or-to-workspace-up; }
    Mod+Shift+J { move-window-down-or-to-workspace-down; }

    Alt+Tab { focus-window-down; }
    Alt+Shift+Tab { focus-window-up; }

    ,XF86AudioMute { spawn "pamixer" "--toggle-mute"; }
    ,XF86AudioRaiseVolume { spawn "pamixer" "-i" "5"; }
    ,XF86AudioLowerVolume { spawn "pamixer" "-d" "5"; }

    ,XF86MonBrightnessUp { spawn "brightnessctl" "set" "+5%"; }
    ,XF86MonBrightnessDown { spawn "brightnessctl" "set" "5%-"; }
${lib.concatMapStrings (line: "    ${line}\n") rofiBinds}${lib.concatMapStrings (line: "    ${line}\n") config.sensible.niri.keymaps}}

${lib.concatStringsSep "\n" config.sensible.niri.extraConfig}
''
