name: Flake metadata check
run-name: Ensuring validity of flake metadata
on:
  pull_request:
    types: [opened, synchronize, reopened, closed]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: cachix/install-nix-action@v31
      - uses: extractions/setup-just@v3
      - uses: unfunco/setup-gum@main
      - run: just test
